### ISSUE TITLE
Remove Apache Spark dependency, and/or figure out how to keep its annoying dependencies out of eclipse suggestions

### ISSUE THREAD

**Issue by kevinmilner** [opensha/opensha-dev#30]
We added Spark as an opensha-dev dependency at @field-usgs's request. Unfortunately, it comes with a lot of annoyances. It is very bloated, and comes with a really complicated dependency tree.

The most annoying consequence is that it has contains an entire "shaded" version of Google Guava, so, for example, whenever I try to auto-complete an import of Preconditions, the default one becomes `avro.shaded.com.google.common.base.Preconditions` instead of the real version. It also contains outdated version of other libraries, such as apache commons-lang (as opposed to commons-lang3), which causes confusion if you're importing anything from that library.

@field-usgs, are you still using it or did you find similar/simpler functionality with [Smile](https://github.com/haifengl/smile)? I know you tried both out, are both still needed or did you settle on one?

If we still need Spark in here, then I'll look for ways to make it less annoying in eclipse (not yet sure how)

**Comment by field-usgs** [comment]
Go ahead and comment out where used (NearestNeighborDeclustering) and delete the library.  It didn’t work anyway.



From: Kevin Milner ***@***.***>
Date: Thursday, June 3, 2021 at 7:02 PM
To: opensha/opensha-dev ***@***.***>
Cc: Field, Ned ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] [opensha/opensha-dev] Remove Apache Spark dependency, and/or figure out how to keep its annoying dependencies out of eclipse suggestions (#30)



 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



We added Spark as an opensha-dev dependency at @field-usgs<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ffield-usgs&data=04%7C01%7Cfield%40usgs.gov%7Ce6373d72b735470df5bc08d926f46883%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637583653434966358%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=we0Xop%2Bm0ccpOasLNgAUZWGjwGMCVBseBHn80w10KQw%3D&reserved=0>'s request. Unfortunately, it comes with a lot of annoyances. It is very bloated, and comes with a really complicated dependency tree.

The most annoying consequence is that it has contains an entire "shaded" version of Google Guava, so, for example, whenever I try to auto-complete an import of Preconditions, the default one becomes avro.shaded.com.google.common.base.Preconditions instead of the real version. It also contains outdated version of other libraries, such as apache commons-lang (as opposed to commons-lang3), which causes confusion if you're importing anything from that library.

@field-usgs<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ffield-usgs&data=04%7C01%7Cfield%40usgs.gov%7Ce6373d72b735470df5bc08d926f46883%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637583653434976318%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=6f6qWOeAi4cpdzgnflNJjmAn6PPe%2F6o0cvxV2uyqd4E%3D&reserved=0>, are you still using it or did you find similar/simpler functionality with Smile<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fhaifengl%2Fsmile&data=04%7C01%7Cfield%40usgs.gov%7Ce6373d72b735470df5bc08d926f46883%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637583653434986277%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Kitc%2F%2FLIF0Z87Zc3R%2FZB1wZChTT%2BgSgFppjcmlx8L0E%3D&reserved=0>? I know you tried both out, are both still needed or did you settle on one?

If we still need Spark in here, then I'll look for ways to make it less annoying in eclipse (not yet sure how)

**Comment by kevinmilner** [comment]
Done in 4e19a5db7051a3486cfb47ce16b6c9aac806d3c3
